<div class="show-for-large-up">
<a href="#" class="scrollToTop"><i class="fa fa-chevron-circle-up fa-2x"></i></a>
</div>
<div class="super-header show-for-small-only">
    <div class="super-header-content row collapse">
        <div class="columns small-12 sheader-height">
            <div class="right">
                <a class="right-off-canvas-toggle cart-button" href="#">My Cart (<?php
    $_cartQty = Mage::getSingleton('checkout/cart')->getItemsCount();
    echo $_cartQty;
    ?>)</a>
                <?php /*echo $this->getChildHtml('top_cart')*/ ?>
            </div>
            <div class="right">
                <?php echo $this->getChildHtml('mini_account') ?>
            </div>
        </div>
    </div>
</div>

<div class="super-header show-for-medium-up">
    <div class="super-header-content row collapse">
        <div>
                <!-- <div class="welcome-msg left">
                    <p><?php echo $this->getWelcome() ?> <?php echo $this->getAdditionalHtml() ?></p>
                </div> -->
                <div class="right">
                    <?php echo $this->getChildHtml('store_switcher') ?>
                </div>
                <div class="right lang-border">
                    <?php echo $this->getChildHtml('store_language') ?>
                </div>
                <div class="right">
                    <?php echo $this->getChildHtml('store_currency_selector') ?>
                </div>
                <div class="right">
                    <?php //echo $this->getChildHtml('mini_account') ?>
                </div>
        </div>
    </div>
    <!-- static content only for show -->
    <div class="top-menu row">
        <!-- <div class="row"> -->
          <ul class="account-options left">
            <li><a href="#">my account</a></li>
            <li><a href="#">my wish list</a></li>
            <li><a href="#">my cart</a></li>
            <li><a href="#">login</a></li>
          </ul>
          <div class="language-selector right">
            <span>your language: </span>
            <span class="selected"><a href="#">English</a>
              <!-- <ul>
                <li><a href="#">English</a></li>
                <li><a href="#">Spanish</a></li>
              </ul> -->
            </span>
          </div>
        <!-- </div> -->
      </div><!-- top-menu -->
</div>

<header class="site-header">
    <div class="site-header-content row">
            <div class="site-nav columns small-12 custom-column show-for-small-only">
                <nav class="top-bar" data-topbar>
                    <ul class="title-area">
                        <li class="name">                                                    
                            <?php if ($this->getIsHomePage()):?>
                            <!-- <h1 class="site-logo">
                                <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="site-logo">
                                    <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="mobile-logo" width="200px"/>
                                </a>
                            </h1> -->
                            <?php else:?>
                                <!-- <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo">
                                    <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="mobile-logo" width="200px"/></a> -->
                            <?php endif?>                                                    
                        </li>
                        <!-- <li class="toggle-topbar menu-icon"><a href="#"><span><?php echo $this->__('Menu') ?></span></a></li> -->
                    </ul>
                    <!-- <section class="top-bar-section">
                        
                        <ul class="right">
                            <?php echo $this->getChildHtml('topSearch') ?>
                            <?php echo $this->getChildHtml('topMenu') ?>
                        </ul>
                    </section> -->
                </nav>
            </div>
            <div class="site-identity columns large-3 medium-5 hide-for-small">
                <?php if ($this->getIsHomePage()):?>
                    <!-- <h1 class="site-logo">
                        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="site-logo">
                            <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" width="180px"/>
                        </a>
                    </h1> -->
                <?php else:?>
                    <!-- <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo">
                        <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" width="180px"/></a> -->
                <?php endif?>
                </div>

                <!-- <div class="site-search columns large-6 medium-8 hide-for-small">
                    <?php echo $this->getChildHtml('topSearch') ?>
                </div> -->
                <!-- <div class="columns large-3 medium-4 small-2 text-right top-cart-padd show-for-medium-up">
                <a class="right-off-canvas-toggle cart-button" href="#">My Cart (<?php
                    $_cartQty = Mage::getSingleton('checkout/cart')->getItemsCount();
                    echo $_cartQty;
                    ?>)</a>
                <?php /*echo $this->getChildHtml('top_cart')*/ ?>
                            </div> -->


    </div>
</header>
    <div class="site-nav row show-for-medium-up">
            <div class="columns large-12 custom-column sticky">
                <nav class="top-bar">
                    <p class="left slogan"><?php echo $this->getWelcome() ?> <?php echo $this->getAdditionalHtml() ?></p>
                    <ul class="right menu">
                      <li><a href="#">home</a></li>
                      <li><a href="#">about</a></li>
                      <li><a href="#">customer service</a></li>
                      <li><a href="#">site map</a></li>
                      <li><a href="#">search terms</a></li>
                      <li><a href="#">contacts</a></li>
                    </ul>
                </nav>
            </div>
    </div>
